// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzRX8a-0DJxndAzRff6W0L-4Hk2csdXzY',
    appId: '1:686899616534:web:9ade2a7b47cb2341f84e37',
    messagingSenderId: '686899616534',
    projectId: 'geoweather-9d250',
    authDomain: 'geoweather-9d250.firebaseapp.com',
    storageBucket: 'geoweather-9d250.appspot.com',
    measurementId: 'G-WJ7RZ85PD8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOXDIGqpLC5MPGpIpTnPREDWSEq-V4qKo',
    appId: '1:686899616534:android:26c114b62a4e6bcef84e37',
    messagingSenderId: '686899616534',
    projectId: 'geoweather-9d250',
    storageBucket: 'geoweather-9d250.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp0T_fX8ScPbFzoO9ObeZ2ZqX3OVAaLe4',
    appId: '1:686899616534:ios:11c61548c6bf210ff84e37',
    messagingSenderId: '686899616534',
    projectId: 'geoweather-9d250',
    storageBucket: 'geoweather-9d250.appspot.com',
    iosBundleId: 'com.example.newtokteckTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp0T_fX8ScPbFzoO9ObeZ2ZqX3OVAaLe4',
    appId: '1:686899616534:ios:11c61548c6bf210ff84e37',
    messagingSenderId: '686899616534',
    projectId: 'geoweather-9d250',
    storageBucket: 'geoweather-9d250.appspot.com',
    iosBundleId: 'com.example.newtokteckTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzRX8a-0DJxndAzRff6W0L-4Hk2csdXzY',
    appId: '1:686899616534:web:7af2d68e7045dad9f84e37',
    messagingSenderId: '686899616534',
    projectId: 'geoweather-9d250',
    authDomain: 'geoweather-9d250.firebaseapp.com',
    storageBucket: 'geoweather-9d250.appspot.com',
    measurementId: 'G-YJZNY07318',
  );
}
